server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    #druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.126.3:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logging-config.xml
  level: 
    com.jt.mapper: debug
